import Papa from "papaparse";
import type { Deal } from "@/lib/analytics";
import { formatUsdShort } from "@/lib/analytics";

const BRAND = {
  name: "Deal IQ AI",
  color: "6366f1",
  tagline: "Intelligence · Advisory · Execution",
};

function today() {
  return new Date().toISOString().slice(0, 10);
}

function trigger(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ---------- CSV ----------
export function exportCsv(deals: Deal[]): void {
  const rows = deals.map((d) => ({
    date: d.deal_date ?? "",
    buyer: d.buyer ?? "",
    target: d.target ?? "",
    sector: d.sector ?? "",
    country: d.country ?? "",
    deal_type: d.deal_type ?? "",
    stake_pct: d.stake_percent ?? "",
    value_usd: d.normalized_value_usd ?? "",
    value_raw: d.value_raw ?? "",
    status: d.status ?? "",
  }));
  const csv = Papa.unparse(rows);
  trigger(new Blob([csv], { type: "text/csv" }), `deal-iq-export-${today()}.csv`);
}

// ---------- JSON ----------
export function exportJson(deals: Deal[]): void {
  const payload = {
    exported_by: BRAND.name,
    exported_at: new Date().toISOString(),
    count: deals.length,
    deals,
  };
  trigger(
    new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }),
    `deal-iq-export-${today()}.json`
  );
}

// ---------- PDF (via print-to-PDF) ----------
export function exportPdf(deals: Deal[], title = "Deal Pipeline Report"): void {
  const win = window.open("", "_blank");
  if (!win) return;
  const total = deals.reduce((s, d) => s + (d.normalized_value_usd ?? 0), 0);
  const rows = deals
    .map(
      (d) => `<tr>
        <td>${d.deal_date ?? "—"}</td>
        <td><strong>${d.buyer ?? "—"}</strong></td>
        <td>${d.target ?? "—"}</td>
        <td>${d.sector ?? "—"}</td>
        <td>${d.country ?? "—"}</td>
        <td style="text-align:right">${d.normalized_value_usd ? formatUsdShort(d.normalized_value_usd) : "—"}</td>
        <td style="text-transform:capitalize">${d.status ?? "—"}</td>
      </tr>`
    )
    .join("");

  win.document.write(`<!DOCTYPE html><html><head><title>${title}</title>
<style>
body{font-family:'Helvetica',Arial,sans-serif;max-width:1000px;margin:40px auto;padding:0 30px;color:#0f172a}
.brand{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #${BRAND.color};padding-bottom:16px;margin-bottom:24px}
.brand .name{font-size:11px;font-weight:700;letter-spacing:2px;color:#${BRAND.color};text-transform:uppercase}
.brand .tag{font-size:11px;color:#64748b;margin-top:2px}
h1{font-size:22px;margin:8px 0 4px}
.meta{font-size:11px;color:#64748b}
.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0}
.stat{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:12px}
.stat .l{font-size:10px;color:#64748b;text-transform:uppercase;letter-spacing:0.5px}
.stat .v{font-size:18px;font-weight:700;color:#0f172a;margin-top:4px}
table{width:100%;border-collapse:collapse;margin-top:16px;font-size:11px}
th{background:#f1f5f9;text-align:left;padding:8px 10px;border-bottom:2px solid #cbd5e1;font-size:10px;text-transform:uppercase;color:#475569}
td{padding:8px 10px;border-bottom:1px solid #f1f5f9}
.footer{margin-top:32px;padding-top:12px;border-top:1px solid #e2e8f0;font-size:10px;color:#94a3b8;text-align:center}
@media print{body{margin:20px}table{font-size:10px}}
</style></head><body>
<div class="brand">
  <div><div class="name">${BRAND.name}</div><div class="tag">${BRAND.tagline}</div></div>
  <div style="text-align:right" class="meta">${new Date().toLocaleDateString()}<br/>CONFIDENTIAL</div>
</div>
<h1>${title}</h1>
<div class="meta">${deals.length} transactions · Total value ${formatUsdShort(total)}</div>
<div class="stats">
  <div class="stat"><div class="l">Deals</div><div class="v">${deals.length}</div></div>
  <div class="stat"><div class="l">Total Value</div><div class="v">${formatUsdShort(total)}</div></div>
  <div class="stat"><div class="l">Avg Deal Size</div><div class="v">${deals.length ? formatUsdShort(total / deals.length) : "—"}</div></div>
</div>
<table>
<thead><tr><th>Date</th><th>Buyer</th><th>Target</th><th>Sector</th><th>Country</th><th style="text-align:right">Value</th><th>Status</th></tr></thead>
<tbody>${rows || '<tr><td colspan="7" style="text-align:center;color:#94a3b8;padding:40px">No deals</td></tr>'}</tbody>
</table>
<div class="footer">Generated by ${BRAND.name} · ${new Date().toLocaleString()} · Confidential — for internal use only.</div>
</body></html>`);
  win.document.close();
  setTimeout(() => win.print(), 300);
}

// ---------- PPTX ----------
export async function exportPptx(deals: Deal[], title = "Deal Pipeline"): Promise<void> {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = BRAND.name;
  pptx.company = BRAND.name;
  pptx.title = title;

  const total = deals.reduce((s, d) => s + (d.normalized_value_usd ?? 0), 0);
  const live = deals.filter((d) => d.status === "live" || d.status === "announced").length;

  // ── Slide 1: Title
  const s1 = pptx.addSlide();
  s1.background = { color: "0F172A" };
  s1.addText(BRAND.name, {
    x: 0.5, y: 0.4, w: 12, h: 0.5,
    fontSize: 10, color: BRAND.color, bold: true, fontFace: "Helvetica",
    charSpacing: 4,
  });
  s1.addText(title, {
    x: 0.5, y: 2.5, w: 12, h: 1.5,
    fontSize: 44, color: "FFFFFF", bold: true, fontFace: "Helvetica",
  });
  s1.addText(BRAND.tagline, {
    x: 0.5, y: 4.1, w: 12, h: 0.5,
    fontSize: 16, color: "94A3B8", fontFace: "Helvetica",
  });
  s1.addText(new Date().toLocaleDateString() + "  ·  CONFIDENTIAL", {
    x: 0.5, y: 6.8, w: 12, h: 0.3,
    fontSize: 10, color: "64748B", fontFace: "Helvetica",
  });

  // ── Slide 2: KPI Overview
  const s2 = pptx.addSlide();
  s2.addText("Executive Overview", {
    x: 0.5, y: 0.3, w: 12, h: 0.6,
    fontSize: 28, bold: true, color: "0F172A", fontFace: "Helvetica",
  });
  const stats = [
    { label: "Total Deals", value: String(deals.length) },
    { label: "Total Value", value: formatUsdShort(total) },
    { label: "Active / Live", value: String(live) },
    { label: "Avg. Deal Size", value: deals.length ? formatUsdShort(total / deals.length) : "—" },
  ];
  stats.forEach((st, i) => {
    const x = 0.5 + i * 3.1;
    s2.addShape(pptx.ShapeType.roundRect, {
      x, y: 1.4, w: 2.9, h: 1.8,
      fill: { color: "F8FAFC" }, line: { color: "E2E8F0", width: 1 }, rectRadius: 0.1,
    });
    s2.addText(st.label, {
      x: x + 0.2, y: 1.55, w: 2.6, h: 0.35,
      fontSize: 11, color: "64748B", bold: true, charSpacing: 2,
    });
    s2.addText(st.value, {
      x: x + 0.2, y: 1.95, w: 2.6, h: 1.1,
      fontSize: 32, color: "0F172A", bold: true, fontFace: "Helvetica",
    });
  });

  // Top sectors bar chart
  const sectorMap = new Map<string, number>();
  deals.forEach((d) => {
    const k = d.sector ?? "Unknown";
    sectorMap.set(k, (sectorMap.get(k) ?? 0) + (d.normalized_value_usd ?? 0));
  });
  const topSectors = Array.from(sectorMap.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 6);

  if (topSectors.length > 0) {
    s2.addChart(pptx.ChartType.bar, [{
      name: "Value ($M)",
      labels: topSectors.map((x) => x[0]),
      values: topSectors.map((x) => Math.round(x[1] / 1e6)),
    }], {
      x: 0.5, y: 3.6, w: 12, h: 3.5,
      chartColors: [BRAND.color],
      showTitle: true, title: "Top Sectors by Deal Value ($M)",
      titleFontSize: 14, titleColor: "0F172A",
      showLegend: false, catAxisLabelFontSize: 10, valAxisLabelFontSize: 10,
    });
  }

  // ── Slide 3: Top Deals table
  const s3 = pptx.addSlide();
  s3.addText("Top 15 Deals", {
    x: 0.5, y: 0.3, w: 12, h: 0.6,
    fontSize: 28, bold: true, color: "0F172A", fontFace: "Helvetica",
  });
  const top15 = [...deals]
    .filter((d) => d.normalized_value_usd)
    .sort((a, b) => (b.normalized_value_usd ?? 0) - (a.normalized_value_usd ?? 0))
    .slice(0, 15);

  const tblRows = [
    [
      { text: "Date", options: { bold: true, color: "FFFFFF", fill: { color: BRAND.color } } },
      { text: "Buyer", options: { bold: true, color: "FFFFFF", fill: { color: BRAND.color } } },
      { text: "Target", options: { bold: true, color: "FFFFFF", fill: { color: BRAND.color } } },
      { text: "Sector", options: { bold: true, color: "FFFFFF", fill: { color: BRAND.color } } },
      { text: "Value", options: { bold: true, color: "FFFFFF", fill: { color: BRAND.color }, align: "right" } },
    ],
    ...top15.map((d) => [
      { text: d.deal_date ?? "—" },
      { text: d.buyer ?? "—" },
      { text: d.target ?? "—" },
      { text: d.sector ?? "—" },
      { text: d.normalized_value_usd ? formatUsdShort(d.normalized_value_usd) : "—", options: { align: "right" as const } },
    ]),
  ];
  s3.addTable(tblRows, {
    x: 0.5, y: 1.2, w: 12,
    fontSize: 10, fontFace: "Helvetica",
    border: { type: "solid", pt: 0.5, color: "E2E8F0" },
    colW: [1.5, 3, 3, 2, 2.5],
  });

  // ── Slide 4: Closing
  const s4 = pptx.addSlide();
  s4.background = { color: "F8FAFC" };
  s4.addText("Thank You", {
    x: 0.5, y: 2.8, w: 12, h: 1.2,
    fontSize: 54, bold: true, color: "0F172A", align: "center", fontFace: "Helvetica",
  });
  s4.addText(BRAND.name + "  ·  " + BRAND.tagline, {
    x: 0.5, y: 4.1, w: 12, h: 0.5,
    fontSize: 14, color: "64748B", align: "center", fontFace: "Helvetica",
  });
  s4.addText("CONFIDENTIAL · " + new Date().toLocaleDateString(), {
    x: 0.5, y: 6.8, w: 12, h: 0.3,
    fontSize: 9, color: "94A3B8", align: "center", fontFace: "Helvetica",
  });

  await pptx.writeFile({ fileName: `deal-iq-pipeline-${today()}.pptx` });
}
