// src/lib/ui/provenance.ts
//
// PHASE 7G — how a result was produced, and the exact words used to say so.
//
// Kept out of the component (and free of "use client") so the wording is pure,
// importable from anywhere, and directly assertable: the honesty rules below are
// properties of these strings, not of rendered markup.
//
// THE RULE
// A provenance claim is only ever made about the specific operation that actually
// happened. There is deliberately NO "processed locally" / "on-device" state, because
// no partner-facing generation in this app runs on-device: browser AI is advisory-only
// by policy (see on-device-policy.ts) and every module route runs server-side. Adding
// such a label would be exactly the false claim this phase exists to prevent. If
// on-device generation is ever introduced it gets its own variant, set only by the code
// path that genuinely ran locally.

export type Provenance =
  | { kind: "reused"; similarity?: number }
  | { kind: "norequest" }
  | { kind: "cloud"; provider?: string | null; model?: string | null }
  | null;

/** Build provenance from an API response, inventing nothing that is not in it. */
export function provenanceFrom(j: {
  cached?: boolean;
  semanticSimilarity?: number;
  viaT0?: boolean;
  provider?: string | null;
  model?: string | null;
}): Provenance {
  // Order matters: a deterministic answer is a stronger, more specific claim than a
  // reuse, and only ONE claim is ever made about a single result.
  if (j.viaT0) return { kind: "norequest" };
  if (j.cached) return { kind: "reused", similarity: j.semanticSimilarity };
  if (j.provider) return { kind: "cloud", provider: j.provider, model: j.model ?? null };
  return null;
}

/**
 * The wording. Returns null when provenance is unknown, so the caller renders nothing
 * rather than guessing at how a result was produced.
 */
export function describeProvenance(provenance: Provenance): { label: string; title: string } | null {
  if (!provenance) return null;

  if (provenance.kind === "reused") {
    // An exact match is stated as exact; a near match says so rather than implying the
    // inputs were identical.
    const exact = provenance.similarity === undefined || provenance.similarity >= 0.999;
    return {
      label: "Reused earlier result — no AI call",
      title: exact
        ? "The same inputs were generated before, so the stored result was returned. No AI request was made and nothing was charged."
        : `A near-identical earlier result (${Math.round((provenance.similarity ?? 0) * 100)}% match) was returned. No AI request was made and nothing was charged.`,
    };
  }

  if (provenance.kind === "norequest") {
    return {
      label: "Computed without AI",
      title: "Every field was already known, so this was produced by the platform's own rules. No AI request was made and nothing was charged.",
    };
  }

  const who = [provenance.provider, provenance.model].filter(Boolean).join(" · ");
  return {
    label: who ? `Generated by ${who}` : "Generated by AI",
    title: "This result came from a live AI request using your configured key.",
  };
}
