/**
 * Deal IQ AI — Consulting-grade deck quality gates.
 *
 * Three responsibilities:
 *   1. WORD_LIMITS + fitText()       — enforce the "max 45 words / slide" Big4 bar
 *                                      by truncating at a word boundary. Containers
 *                                      are NEVER expanded to fit overflowing text.
 *   2. validateDeckJSON()            — banned-filler-phrase gate + structural
 *                                      invariants (TSA service count, synergy maths).
 *   3. assertSlideHasVisual()        — every content slide must carry at least one
 *                                      chart / table / callout / timeline / card grid.
 */

export const WORD_LIMITS = {
  slideTitle:    15,
  bulletPoint:   18,
  cardBody:      35,
  metricValue:   2, // e.g. "₹1.89B"
  metricLabel:   5,
  tableCell:     20,
  justification: 60, // verdict / recommendation only
  footnote:      25,
} as const;

export type WordLimitField = keyof typeof WORD_LIMITS;

/**
 * Strip residual markdown / formatting artifacts so nothing like `**`, `##`,
 * backticks, blockquote `>` or list markers ever reaches a slide. Applied
 * automatically by `fitText`, so every text container in the deck is clean.
 */
export function clean(text: string): string {
  return (text ?? "")
    .replace(/\*\*/g, "")              // bold markers
    .replace(/(^|\s)\*(\S)/g, "$1$2")  // stray opening italics
    .replace(/(\S)\*(\s|$)/g, "$1$2")  // stray closing italics
    .replace(/`+/g, "")                // code ticks
    .replace(/~~/g, "")                // strikethrough
    .replace(/\[(\d+)\]/g, "")         // citation refs
    .replace(/!?\[([^\]]*)\]\([^)]*\)/g, "$1") // md links → label text
    .replace(/^\s{0,3}#{1,6}\s+/, "")          // leading heading hashes
    .replace(/^\s{0,3}>\s?/, "")               // leading blockquote
    .replace(/^\s{0,3}(?:[-*+]|\d+\.)\s+/, "") // leading list marker
    .replace(/[ \t]{2,}/g, " ")
    .trim();
}

/**
 * Truncate `text` to the word budget for `field`, appending an ellipsis when
 * trimmed. Always trims at a word boundary; never expands the container.
 * Markdown artifacts are stripped first via `clean`.
 */
export function fitText(text: string, field: WordLimitField): string {
  const words = clean(text).split(/\s+/).filter(Boolean);
  const max = WORD_LIMITS[field];
  if (words.length <= max) return words.join(" ");
  return words.slice(0, max).join(" ") + "…";
}

/** Count words in a string (whitespace-delimited). */
export function wordCount(text: string): number {
  return (text ?? "").trim().split(/\s+/).filter(Boolean).length;
}

// ---------------------------------------------------------------------------
// Banned filler phrases — McKinsey/Bain/BCG "wall of mush" tells. None of these
// may survive into a client-facing slide.
// ---------------------------------------------------------------------------
export const BANNED_PHRASES = [
  "the company will benefit",
  "significant value creation",
  "our analysis shows",
  "it is important to note",
  "going forward",
  "world-class",
  "best practices",
  "synergistic opportunities",
  "generated by ai",
  "no warranties",
] as const;

/**
 * Remove banned filler phrases from a body of text (case-insensitive), collapsing
 * the whitespace left behind. Used to scrub AI prose BEFORE it reaches a slide so
 * the deck genuinely contains none — and so `validateDeckJSON` passes cleanly.
 */
export function scrubBannedPhrases(text: string): string {
  let out = text ?? "";
  for (const phrase of BANNED_PHRASES) {
    const re = new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "ig");
    out = out.replace(re, "");
  }
  // tidy up doubled spaces / orphan punctuation left by removal.
  // IMPORTANT: collapse only spaces/tabs — NEVER newlines, or the markdown
  // line structure the extractors rely on (headings, bullets, tables) is lost.
  return out.replace(/[ \t]{2,}/g, " ").replace(/[ \t]+([.,;:—-])/g, "$1").trim();
}

/**
 * Quality gate — run before every PPTX render. Throws on any banned phrase or
 * broken structural invariant so a sub-standard deck never ships.
 */
export function validateDeckJSON(json: unknown, docType: string): void {
  const str = JSON.stringify(json).toLowerCase();

  for (const phrase of BANNED_PHRASES) {
    if (str.includes(phrase)) {
      throw new Error(`Banned phrase in output: "${phrase}"`);
    }
  }

  // TSA must have >= 8 service lines
  if (docType === "tsa") {
    const svc = (json as { services?: unknown[] })?.services ?? [];
    if (svc.length < 8) {
      throw new Error(`TSA has only ${svc.length} service lines; minimum 8 required`);
    }
  }

  // Synergy arithmetic check: Year-3 revenue + cost synergy must equal net run-rate
  const sm = (json as { synergy_model?: SynergyMathShape })?.synergy_model;
  if (sm) {
    const expected = (sm.revenue_synergy?.y3 ?? 0) + (sm.cost_synergy?.y3 ?? 0);
    if (Math.abs(expected - (sm.net_run_rate_y3 ?? 0)) > 1) {
      throw new Error("Synergy arithmetic error: Rev+Cost ≠ Net");
    }
  }
}

type SynergyMathShape = {
  revenue_synergy?: { y3?: number };
  cost_synergy?: { y3?: number };
  net_run_rate_y3?: number;
};

// ---------------------------------------------------------------------------
// Mandatory visual element check
// ---------------------------------------------------------------------------

/**
 * A lightweight per-slide visual tracker. Template renderers call `mark()` after
 * they emit a chart / table / callout / timeline / card grid; the exporter calls
 * `assert()` once the slide is fully composed.
 */
export class VisualGuard {
  private present = false;

  mark(): void {
    this.present = true;
  }

  hasVisual(): boolean {
    return this.present;
  }

  assert(title: string): void {
    if (!this.present) {
      throw new Error("Slide has no visual element: " + title);
    }
  }
}
